### PR TITLE
Open Github from link

### LINKED ISSUE #526: GitHub links don't offer the app from K9 Mail
When I receive a notification email from GitHub and tap on the link to "View this on GitHub", I get a list of browsers as a choice, but not the GitHub app. However, if I tap and hold on the link, then choose Open Link, I now have a choice of apps including the GitHub app. Maybe a bug in K9 Mail or could it be in the GitHub app?

### PR DESCRIPTION
**Pull request by wbmrcb**
This should fix #526 
http://developer.android.com/reference/android/content/Intent.html#CATEGORY_BROWSABLE

### CODE REVIEW

**Comment by fadils** [comment]
Merged to development

**Comment by hzsweers** [comment]
@fadils what does that tag mean here?

**Comment by larsgrefer** [comment]
@wbmrcb You might want to rebase your changes on the current master?

**Comment by fadils** [comment]
@hzsweers it's related to our previous strategy where everything should be merged to "development" branch for testing.. Didn't work though. :disappointed:

**Comment by EzraBrooks** [comment]
@fadils Technically that is how you're supposed to do it; [GitHub Flow](https://guides.github.com/introduction/flow/) dictates that the master branch should always be deployable. Development should be done in a separate branch, and ideally in multiple separate branches for different changes.

**Pull request closed without merging**
