### PR TITLE
Make tests stable on api level 21 and fix some typo

### PR DESCRIPTION
**Pull request by hkliya**
```
getInstrumentation().sendStringSync(text);
```
On api level 21, the tests are not stable, that's because after call `sendStringSync("xxx")`, you can't get stable value from `editText.getText()`, according to the official functional test sample, call `waitForIdleSync()` around `sendStringSync()` can fix this.

### CODE REVIEW

**Comment by larsgrefer** [comment]
looks good to me
should be merged

**Comment by jonan** [comment]
Merge relevant commits to Forkhub: https://github.com/jonan/ForkHub/commit/2897b712b83a43134f101082decfc3f2cfff7546 https://github.com/jonan/ForkHub/commit/1b86f9f96c70f58eb69b44e4dffed8872a8eeb68

The other two commits aren't really related to tests.

**Comment by larsgrefer** [comment]
@jonan What is the difference between forkhubs/android and jonan/ForkHub (you are displayed as owner of both) and to which of both should we send our pull requests to?

**Comment by fadils** [comment]
@hkliya can you include the relevant commit only?

**Comment by fadils** [comment]
@larsgrefer FYI forkhubs (with S) is the official spin-off from GitHub. Thus it still shows the contributing history as well as the number stars and forks.
jonan/ForkHub is his own version.

**Comment by larsgrefer** [comment]
@hkliya Just set your master branch back to 835b9ff (removing the unnecessary merge commit)

```git push origin master:835b9ff -f```
(assuming your origin remote is 'https://github.com/hkliya/android.git')

**Comment by jonan** [comment]
@larsgrefer basically forkhubs/android is more focused on features and jonan/ForkHub on order and stability (already usable from Google Play).

You can send PR to whichever you want, I'll try to keep them in sync when commits apply to both anyway.

**Comment by larsgrefer** [comment]
@fadils I was confused because jonan/ForkHub is not marked as fork of this (forkhubs/android) an because @jonan is marked as owner of both repos

**Comment by fadils** [comment]
@larsgrefer I'm confused too.

**Comment by larsgrefer** [comment]
@jonan @fadils In my opinion we should focus on this repository because it's the (more or less) official one. Therefore it's nice that @jonan pulls pull requests to his version, but i'd like to see the contributions of me and others in this repo too.

**Comment by jonan** [comment]
@larsgrefer no worries, simply contribute to this repo.

If anything applies to jonan/ForkHub I'll cherry-pick it.

**Comment by larsgrefer** [comment]
@jonan Ok, thanks

Then i just wait for reactions to my 7 open pull requests ;)

In the meantime we can merge this request via #777

**Comment by hkliya** [comment]
Sorry for my late response. I will include only relative commits in one PR in the future. Thanks!

**Pull request closed without merging**
