### PR TITLE
Clean gradle Project-Structure

### LINKED ISSUE #602: Roadmap: Gradle or Maven?
With several talks, issues reported even some PRs about Gradle support, what exactly is the roadmap? 

And as you can see here https://plus.google.com/+AndroidDevelopers/posts/9KeE69UR4PG, Maven support is dropped by AndroidStudio.

Moving to Gradle, personally I think, is an awesome thing to do.
Also, in PR #378 @atermenji mentioned about concerns for Eclipse and IntelliJ users. Gradle is supported by two IDEs if I'm not mistaken, although it's not their default build systems.

So, are you guys planning to move to Gradle?

Could someone please elaborate what the roadmap is?

### LINKED ISSUE #659: Restructure project hierarchy to be a proper gradle project
Right now it's still set up like an eclipse project, just with hook-ins to support gradle. I will try to do this today and PR back in tonight. I'm suggesting this on the assumption that you guys have switched over to Android Studio now that it's stable, so please let me know if this isn't viable right now :smiley:

### PR DESCRIPTION
**Pull request by larsgrefer**
Using a clean directory-structure for gradle including the instumentation-tests
#748 
fixes #602
fixes #659

### CODE REVIEW

**Comment by larsgrefer** [comment]
@jonan @fadils What is your option on dropping the maven and eclipse support and using a clean gradle build structure like mentioned here: http://developer.android.com/tools/building/configuring-gradle.html ?

**Comment by hzsweers** [comment]
This is solid, and much needed. With the number of changes though, it's going to break a lot of existing pull requests. Need to think about if it's better to bite the bullet and do this now, or try to resolve those first (but then you'd probably have to close and re-open after those updates). Leaning towards the latter, but since the work is on you for this I want to see what you think as well @larsgrefer

**Comment by larsgrefer** [comment]
I think we should wait until the most mergeable pull requests are merged.
But in the meantime we can merge at least #754

I try to rebase this whenever needed so it stays mergeable

**Comment by hzsweers** [comment]
I'd rather just do them all together in one pull request, rather than have the same commit appear in both. I've commented/addressed most of the open PRs right now, so waiting for responses and hopefully should get them resolved soon.

**Comment by larsgrefer** [comment]
Okay, but if you'd merge #754 i'll remove the commit from this PR

**Comment by hzsweers** [comment]
Still rather do them together in this pull request, please just wait.

**Comment by hzsweers** [comment]
Pulling the trigger on this. The other PRs I've responded to have had enough time

**Comment by hidroh** [comment]
:+1:

**Pull request merged**
