### PR TITLE
Naturalize's suggestions

### PR DESCRIPTION
**Pull request by condda**
Naturalize's renaming suggestions to improve the codebase consistency

### CODE REVIEW

**Comment by hzsweers** [comment]
Who is "Naturalize"?

**Comment by condda** [comment]
Naturalize is a framework that learns the style of a codebase, and suggests revisions to improve stylistic consistency

**Comment by hzsweers** [comment]
I only really agree with the last commit. Remove the other two and I'd be happy to merge

**Comment by condda** [comment]
Cool, I renamed back the identifiers "item" to "menuItem" and "repository" to "fullRepository"

**Comment by hzsweers** [comment]
Can you just remove those commits instead?

**Comment by condda** [comment]
Sure, it's done.

**Pull request merged**
