### PR TITLE
Add missing French translations in values-fr/strings.xml

### PR DESCRIPTION
**Pull request by chteuchteu**

### CODE REVIEW

**Comment by larsgrefer** [comment]
Looks good to me

**Comment by hzsweers** [comment]
@larsgrefer do you speak french? Not sure if you were approving of the commit or the actual translations. Just curious because I want to get a second set of eyes on this

**Comment by chteuchteu** [comment]
Yes I am :) I wouldn't dare pull requesting translations if I wasn't sure they were correct :)

**Comment by hzsweers** [comment]
I believe you, just want to get another fresh speaker to double check if possible. Do you know someone that could chime in here?

**Comment by chteuchteu** [comment]
No problem :) Sure I do!

**Comment by chteuchteu** [comment]
Fixed! :) My bad

**Comment by hzsweers** [comment]
Great! What about the empty `delete_successful` string in e29865e?

**Comment by chteuchteu** [comment]
Good question: I deleted the line in 754b76e :)

**Comment by fadils** [comment]
@chteuchteu it looks better now. Thanks @MrMitch for double checking and of course @hzsweers for nit-picking the PR. :smile: 
Awesome!

**Comment by chteuchteu** [comment]
Thanks for the merging!
I'll work some more on those translations soon (I added the missing ones, but there seems to be some inconsistencies spotted by @MrMitch 's eagle eyes)

**Pull request merged**
