### PR TITLE
Authentication and SDK update started

### PR DESCRIPTION
**Pull request by Meisolsson**
Alright, now here's the thing. 

The new SDK needs some values wich you can get from GitHub. Got to Settings -> Application -> Developer applications (Tab) -> Register new application. After creating it you will be given a client id and a client secret. You also need to provide a callback url. Those values should be placed in the "res/values/config.xml". After that you are good to go, just rememeber to NEVER push your value (We could add a .gitignore for the file).

Also Travis will be able to build but not auth, but we can work around that later.

The login screen is temporary but works.

### CODE REVIEW

**Comment by Meisolsson** [comment]
This should fix #582

**Comment by hzsweers** [comment]
Awesome, I'll review later today.

**Comment by Meisolsson** [comment]
Travis won't handle this since it will assert if it can't fin the value, might be able to set environment variables in Travis so Gradle can read from that. Those variables are not shown in the log and will only build from our repo (http://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings)

**Comment by Meisolsson** [comment]
So that will let us build directly in Travis for release later!

**Comment by hzsweers** [comment]
@Meisolsson reviewed the current commits. Also send me your email if you want to get on the collab slack channel (message me at pandanomic (at) gmail)

**Comment by Meisolsson** [comment]
I'll fix the issues later today.

**Comment by Meisolsson** [comment]
We might have a new problem... GitHub has a new thing called "Third-party application restrictions", noticed it since we use it at forkhub. With that on each user has to as for access to the organization. If the user doesn't have access it will give a 404 error, only when trying to write to a repo from the org (comments, creating issues etc.) but still bad.

**Comment by Meisolsson** [comment]
Looks like we need to revert back to basic auth to fix this... Will look at it later

**Comment by Meisolsson** [comment]
@hzsweers So I talked to GiyHub support and the only way we can bypass the "Third-party application restrictions" is to use basic auth. This means to update add this to the SDK which should be easy.

So what should we do?

**Comment by hzsweers** [comment]
@Meisolsson this looks good. Anything else before we merge?

**Comment by hzsweers** [comment]
The tablayout switch fits all tabs on the screen, and subsequently squishes the test. Can we allow variable length?

victara_tmolpe23 32-21 3hsweers07122015014206

**Comment by Meisolsson** [comment]
No, I think that's all
On Jul 12, 2015 10:41, "Henri (Zac) Sweers" <notifications@github.com> wrote:@Meisolsson this looks good. Anything else before we merge?

**Comment by hzsweers** [comment]
Going to fix the tab thing myself after merge, wasn't introduced in this PR

**Pull request merged**
