### PR TITLE
Losslessly compress PNG files.

### PR DESCRIPTION
**Pull request by XhmikosR**
Before: 244 KB (250.693 bytes)
After:  177 KB (181.893 bytes)

### CODE REVIEW

**Comment by hzsweers** [comment]
What's the compiled release APK size difference?

**Comment by XhmikosR** [comment]
That I don't know. This is the second patch of this nature BTW  https://github.com/forkhubs/android/commit/6fe37338ceea34900fad852b7f3aad1f65e35527

**Comment by larsgrefer** [comment]
@hzsweers While building the apk aapt will compress the ```png```'s too

**Comment by XhmikosR** [comment]
Not sure if it will achieve the same compression though, being that I used
zopfli too.

**Comment by XhmikosR** [comment]
Let alone I run hundreds of passes with pngout etc. So this should be
better.

**Comment by hzsweers** [comment]
It's done. Worst case there's no change in the final APK and the images are a optimized in the repo.

**Pull request merged**
