### PR TITLE
Add Browsable category to intent-filter

### PR DESCRIPTION
**Pull request by geeteshk**
CATEGORY_BROWSABLE - The target activity allows itself to be started by a web browser to display data referenced by a link—such as an image or an e-mail message. Stated here: http://developer.android.com/guide/components/intents-filters.html

### CODE REVIEW

**Comment by larsgrefer** [comment]
good Idea

**Comment by hzsweers** [comment]
@geeteshk could you give a specific example of where this would be used within the context of the app? As far as I can tell, it already intercepts links from my emails.

**Comment by ityulong** [comment]
i don not konw!

**Comment by geeteshk** [comment]
@hzsweers Just for the sake of convention.

**Comment by hzsweers** [comment]
I don't know if convention is the right word for it. Maybe convenience, but I agree we might as well support it.

**Pull request merged**
