### PR TITLE
Support filtering the repositories page list

### PR DESCRIPTION
**Pull request by fadils**
A continuation work based on original @kevinSawicki filtering branch..

cc'ed @jonanp @atermenji

### CODE REVIEW

**Comment by fadils** [comment]
@jonanp Can we merge this? Or is it still under your review?

**Comment by hzsweers** [comment]
You should update your IDE's copyright template ;)

**Comment by fadils** [comment]
What about it?

**Comment by hzsweers** [comment]
The new files here all say Copyright (c) Github **2012**

**Comment by fadils** [comment]
Good catch. Thanks.

**Comment by jonanp** [comment]
@fadils I'm still reviewing and I think I have some issues, I'll give you more details soon.

**Comment by fadils** [comment]
@jonanp Will wait for the feedbacks.

**Comment by hzsweers** [comment]
@jonan @fadils what's the status?

**Comment by fadils** [comment]
@hzsweers probably need to resolve many conflicts before it can be merged once again. Let's set this to the release after the first one.

But before continueing this thing, was wondering what feedbacks @jonan is going to give. It will be useful to get his feedback, then continue the development.
Meanwhile, if you have some inputs too regarding this, that would be good too.

**Comment by fadils** [comment]
closed via #796

**Pull request closed without merging**
