### PR TITLE
removing IDE specific files (IntelliJ/AndroidStudio and Eclipse)

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by StefMa** [comment]
Are these files in gitignore too? Not that they put it in in the next commit again..

**Comment by hzsweers** [comment]
I asked him in another pull request to fix the `.idea` line in gitignore

**Comment by hzsweers** [comment]
This is part of #756

**Comment by larsgrefer** [comment]
@StefMa @hzsweers Yes, these files are in ```.gitignore``` too.
See line number 98

**Comment by hzsweers** [comment]
@larsgrefer see my comment about this in #756

**Pull request closed without merging**
