### PR TITLE
Let lint fail on errors

### PR DESCRIPTION
**Pull request by larsgrefer**
Let lint fail on errors (but don't on Missing Translations)

### CODE REVIEW

**Comment by hzsweers** [comment]
I actually think we should fail on errors, but we'll have to figure that out separately. Not worth changing the current setup for now

**Comment by larsgrefer** [comment]
When #799, #798 and #759 are merged we can savely set fail on error to true

**Comment by hzsweers** [comment]
Marking errors as warnings is not really what I had in mind for making the
project pass lint inspection, as it ignores problems rather than resolve
them.

**Comment by larsgrefer** [comment]
I dont't like doing it this way, too.
However I think we don't get the ```MissingTranslation``` errors resolved soon and I think just ignoring one specific error is better than ignoring all of them (via ```failOnError false```)

**Comment by hzsweers** [comment]
I'll look more at it when I have some time

**Pull request closed without merging**
