### PR TITLE
Updated Turkish translation

### PR DESCRIPTION
**Pull request by semihyagcioglu**
There has been new string introductions that has not been translated
yet. I translated new strings and polished the rest.

### CODE REVIEW

**Comment by hzsweers** [comment]
Hi @semihyagcioglu, is there someone else that could take a glance at these and review them? Someone else that speaks turkish that is :)

**Comment by semihyagcioglu** [comment]
Hi @hzsweers, sure. I'll ask @ozandeniz maybe he could help with that :)

**Comment by hzsweers** [comment]
Thanks!

**Comment by ozandeniz** [comment]
Looks good to me @semihyagcioglu @hzsweers

**Comment by hzsweers** [comment]
Thanks guys!

**Pull request merged**
